<!-- begin : main content -->
<div id="content">
  <!-- begin : home page wrapper -->
  <div id="wrap">
    <div id="home">
      <!-- begin : layout wrapper -->
      <div class="col">
        <!-- begin : wrapper for cols 1 & 2 -->
        <div id="first" class="col">
        <!-- SWT removed col 1 -->
        <!-- begin : col 2 -->
          <div class="col last">
            <div class="horizontalTabs">
              <ul id="tabsContainer">
                <!-- Tabs generated by global file horizontalTabs.js - parameters are set in local file config_home.js -->
              </ul>
							<div id="tabPaneSet" class="contentwrap">
                  <#include "article/recentArticles.ftl">
              </div>
            </div><!-- end : horizontalTabs -->
            <!-- begin : calls to action blocks -->
            <div class="ctaWrap">
              <div id="cta1">
                <strong>Publish with PLoS</strong>
                <a href="${checklist}">We want to publish your work</a>
              </div>
              <div id="cta2">
                <strong>Have Your Say</strong>
                <a href="${comment}">Add ratings and discussions</a>
              </div>
              <div class="clearer">&nbsp;</div>
            </div>
            <!-- end : calls to action blocks -->
            <div class="block">
              <h2>Featured Review</h2>
              <@s.url id="featured" namespace="/article" action="fetchArticle" articleURI="info:doi/10.1371/journal.pntd.0000065"/>
              <div class="article section lastSection">
                <h3><@s.a href="${featured}" title="Read Open-Access Article">Nod-Like Receptors: Cytosolic Watchdogs for Immunity against Pathogens</@s.a></h3>
                <img src="images/imgPlaceholder_90px.gif" alt="article image" />
                <p>Sirard et al posit that decoding microbial strategies evolved to circumvent Nod-Like Receptors sensing will provide clues for the development of rational therapies aimed at curing and/or preventing common and emerging immunopathologies.</p>
                <div class="clearer">&nbsp;</div>
              </div>
            </div>
            <!-- end block -->
            <div class="block">
              <h2>Featured Research</h2>
              <@s.url id="newNoted1" namespace="/article" action="fetchArticle" articleURI="info:doi/10.1371/journal.pntd.0000056"/>
              <@s.url id="newNoted2" namespace="/article" action="fetchArticle" articleURI="info:doi/10.1371/journal.pntd.0000001"/>
              <@s.url id="newNoted3" namespace="/article" action="fetchArticle" articleURI="info:doi/10.1371/journal.pntd.0000067"/>
              <div class="article section">
                <h3><@s.a href="${newNoted1}" title="Read Open-Access Article">Discordant Evolution of the Adjacent Antiretroviral Genes TRIM22 and TRIM5 in Mammals</@s.a></h3>
                <img src="images/imgPlaceholder_90px.gif" alt="article image" />
                <p>Sawyer, Emerman and Malik present an evolutionary comparison of the human, dog and cow genes responsible for post-entry defense against retroviral infection that indicates a particular structural loop may be a viral recognition motif spanning a hundred million years of mammalian evolution.</p>
                <div class="clearer">&nbsp;</div>
              </div>
              <div class="article section">
                <h3><@s.a href="${newNoted2}" title="Read Open-Access Article">Hemolytic C-Type Lectin CEL-III from Sea Cucumber Expressed in Transgenic Mosquitoes Impairs Malaria Parasite Development</@s.a></h3>
                <img src="images/imgPlaceholder_90px.gif" alt="article image" />
                <p>Yoshida et al genetically modified mosquitoes to express lectin isolated from sea cucumbers in order to study its effects on the development of malaria parasites, and the results show promise as a new approach in the fight against malaria.</p>
                <div class="clearer">&nbsp;</div>
              </div>
              <div class="article section lastSection">
                <h3><@s.a href="${newNoted3}" title="Read Open-Access Article">Analysis of Cells Targeted by Salmonella Type III Secretion In Vivo</@s.a></h3>
                <img src="images/imgPlaceholder_90px.gif" alt="article image" />
                <p>Geddes, Cruz and Heffron challenge prevailing views on the types of cells targeted by <em>Salmonella</em> infection. Their findings could impact treatment of the disease.</p>
                <div class="clearer">&nbsp;</div>
              </div>
            </div><!-- end : block -->
            <div class="other block">
              <h2>Other PLoS Content</h2>
              <div class="section">
                <h3><a href="http://www.plosone.org/"><em>PLoS Neglected Tropical Diseases</em></a></h3>
                <ul class="articles">
                  <li><a href="#" title="Read Open Access Article">Treatment of Helminth Co-Infection in Individuals with HIV-1: A Systematic Review of the Literature</a></li>
                </ul>
              </div>
              <div class="section lastSection">
                <h3><a href="http://www.plosone.org/"><em>PLoS Medicine</em></a></h3>
                <ul class="articles">
                  <li><a href="#" title="Read Open Access Article"><em>Plasmodium vivax</em> Invasion of Human Erythrocytes Inhibited by Antibodies Directed against the Duffy Binding Protein</a></li>
                  <li><a href="#" title="Read Open Access Article">Towards a Vaccine against Plasmodium vivax Malaria</a></li>
                </ul>
              </div>
            </div><!-- end : other block -->
          </div><!-- end : col last -->
        </div><!-- end : wrapper for cols 1 & 2 -->
        <!-- begin : wrapper for cols 3 & 4 -->
        <div id="second" class="col">
          <!-- begin : col 3 -->
          <div class="subcol first">
            <div id="issue" class="block"><h3><a href="${tocStatic}">October 2007 Issue</a></h3><a href="${tocStatic}"><img src="images/imgPlaceholder_251px.gif" alt="issue cover image" /></a></div><!-- keep div#issue hmtl all on one line to avoid extra space below issue image in IE -->
            <!-- end : issue block -->
            <!-- begin : mission block -->
            <div id="mission" class="block">
              <p><strong><em><a href="${info}">PLoS Pathogens</a></em></strong> is an <a href="${license}">open-access</a> journal that publishes important new ideas on bacteria, fungi, parasites, prions, and viruses that contribute to our understanding of the biology of pathogens and pathogen-host interactions.</p>
            </div>
            <!-- end : mission block -->
            <!-- begin : advocacy blocks -->
            <div id="adWrap">
              <script language='JavaScript' type='text/javascript' src='http://ads.plos.org/adx.js'></script>
              <script language='JavaScript' type='text/javascript'>
              <!--
                 if (!document.phpAds_used) document.phpAds_used = ',';
                 phpAds_random = new String (Math.random()); phpAds_random = phpAds_random.substring(2,11);
                 
                 document.write ("<" + "script language='JavaScript' type='text/javascript' src='");
                 document.write ("http://ads.plos.org/adjs.php?n=" + phpAds_random);
                 document.write ("&#38;what=zone:157&#38;source=PAT&#38;block=1");
                 document.write ("&#38;exclude=" + document.phpAds_used);
                 if (document.referrer)
                    document.write ("&#38;referer=" + escape(document.referrer));
                 document.write ("'><" + "/script>");
              //-->
              </script><noscript><a href='http://ads.plos.org/adclick.php?n=aa6c94ce' target='_blank'><img src='http://ads.plos.org/adview.php?what=zone:157&#38;source=PAT&#38;n=aa6c94ce' border='0' alt=''/></a></noscript>
              <script language='JavaScript' type='text/javascript' src='http://ads.plos.org/adx.js'></script>
              <script language='JavaScript' type='text/javascript'>
              <!--
                 if (!document.phpAds_used) document.phpAds_used = ',';
                 phpAds_random = new String (Math.random()); phpAds_random = phpAds_random.substring(2,11);
                 
                 document.write ("<" + "script language='JavaScript' type='text/javascript' src='");
                 document.write ("http://ads.plos.org/adjs.php?n=" + phpAds_random);
                 document.write ("&#38;what=zone:158&#38;source=PAT&#38;block=1");
                 document.write ("&#38;exclude=" + document.phpAds_used);
                 if (document.referrer)
                    document.write ("&#38;referer=" + escape(document.referrer));
                 document.write ("'><" + "/script>");
              //-->
              </script><noscript><a href='http://ads.plos.org/adclick.php?n=a218be41' target='_blank'><img src='http://ads.plos.org/adview.php?what=zone:158&#38;source=PAT&#38;n=a218be41' border='0' alt=''/></a></noscript>
              <script language='JavaScript' type='text/javascript' src='http://ads.plos.org/adx.js'></script>
              <script language='JavaScript' type='text/javascript'>
              <!--
                 if (!document.phpAds_used) document.phpAds_used = ',';
                 phpAds_random = new String (Math.random()); phpAds_random = phpAds_random.substring(2,11);
                 
                 document.write ("<" + "script language='JavaScript' type='text/javascript' src='");
                 document.write ("http://ads.plos.org/adjs.php?n=" + phpAds_random);
                 document.write ("&#38;what=zone:159&#38;source=PAT&#38;block=1");
                 document.write ("&#38;exclude=" + document.phpAds_used);
                 if (document.referrer)
                    document.write ("&#38;referer=" + escape(document.referrer));
                 document.write ("'><" + "/script>");
              //-->
              </script><noscript><a href='http://ads.plos.org/adclick.php?n=aa64352f' target='_blank'><img src='http://ads.plos.org/adview.php?what=zone:159&#38;source=PAT&#38;n=aa64352f' border='0' alt=''/></a></noscript>
            </div>
            <!-- end : advocacy blocks -->
            <!-- begin : stay-connected block -->
            <div id="connect" class="block">
              <h3>Stay Connected</h3>
              <ul>
                  <li><img src="images/icon_alerts_small.gif" alt="email alerts icon" /><a href="${freemarker_config.registrationURL}"><strong>E-mail Alerts</strong></a><br />Sign up for alerts by e-mail</li>
                  <li><img src="images/icon_rss_small.gif" alt="rss icon" /><@s.url action="rssInfo" namespace="/static" includeParams="none" id="rssinfo"/><a href="${Request[freemarker_config.journalContextAttributeKey].baseUrl}${rssPath}"><strong>RSS</strong></a> (<a href="${rssinfo}">What is RSS?</a>)<br />Subscribe to content feed</li>
                  <li><img src="images/icon_join.gif" alt="join PLoS icon" /><a href="http://www.plos.org/support/donate.php" title="Join PLoS: Show Your Support"><strong>Join PLoS</strong></a><br />Support the open-access movement!</li>
              </ul>
            </div>
            <!-- end : stay-connected block -->
            <!-- begin : blog block -->
            <div id="blog" class="block">
              <h3>From the PLoS Blog</h3>
              <p>Read the <a href="http://www.plos.org/cms/blog" title="PLoS Blog">PLoS Blog</a> <a href="http://feeds.feedburner.com/plos/Blog"><img alt="RSS" src="images/feed-icon-inline.gif" /></a> and contribute your views on scientific research and open-access publishing.</p>
              <ul class="articles">
                  <li><a href="http://www.plos.org/cms/node/274">Oops we missed our own birthday</a></li>
                  <li><a href="http://www.plos.org/cms/node/272">Journal Clubs - think of the future!</a></li>
                  <li><a href="http://www.plos.org/cms/node/271">Using open-access articles for student projects</a></li>
              </ul>
            </div>
            <!-- end : blog block -->
          </div><!-- end : subcol first -->
          <!-- end : col 3 -->
          <!-- begin : col 4 -->
          <div class="subcol last">
            <div class="block banner"><!--skyscraper-->
              <script language='JavaScript' type='text/javascript' src='http://ads.plos.org/adx.js'></script>
              <script language='JavaScript' type='text/javascript'>
              <!--
                 if (!document.phpAds_used) document.phpAds_used = ',';
                 phpAds_random = new String (Math.random()); phpAds_random = phpAds_random.substring(2,11);
                 
                 document.write ("<" + "script language='JavaScript' type='text/javascript' src='");
                 document.write ("http://ads.plos.org/adjs.php?n=" + phpAds_random);
                 document.write ("&#38;what=zone:30&#38;source=PAT&#38;block=1&#38;blockcampaign=1");
                 document.write ("&#38;exclude=" + document.phpAds_used);
                 if (document.referrer)
                    document.write ("&#38;referer=" + escape(document.referrer));
                 document.write ("'><" + "/script>");
              //-->
              </script><noscript><a href='http://ads.plos.org/adclick.php?n=ad985188' target='_blank'><img src='http://ads.plos.org/adview.php?what=zone:30&#38;source=PAT&#38;n=ad985188' border='0' alt=''/></a></noscript>
            </div><!-- end : block banner -->
          </div><!-- end : subcol last -->
        </div><!-- end : wrapper for cols 3 & 4 -->
        <div id="lower">&nbsp;</div> <!-- displays lower background image -->
      </div><!-- end : col -->
      <div class="partner">
        <a href="http://www.fedora-commons.org" title="Fedora-Commons.org"><img src="${freemarker_config.context}/images/pone_home_fedoracommons.png" alt="Fedora-Commons.org"/></a>
				<a href="http://www.moore.org" title="Gorden and Betty Moore Foundation"><img src="${freemarker_config.context}/images/pone_home_moore.gif" alt="Moore Foundation"/></a>
        <a href="http://www.mulgara.org/" title="Mulgara.org"><img src="${freemarker_config.context}/images/pone_home_mulgara.gif" alt="Mulgara.org"/></a>
        <a href="http://www.sciencecommons.org/" title="Science Commons"><img src="${freemarker_config.context}/images/pone_home_sciencecommons.gif"  alt="Science Commons"/></a>
				<a href="http://www.unitedlayer.com/" title="UnitedLayer, LLC"><img src="${freemarker_config.context}/images/pone_home_unitedlayer.gif" alt="UnitedLayer, LLC"/></a>
      </div><!-- end : block partners -->
    </div><!-- end : home -->
  </div><!-- end : wrap -->
</div><!-- end : content -->
