<!-- begin : main content -->
<div id="content" class="static">

<h1>Why Publish in <em>PLoS Neglected Tropical Diseases</em>?</h1> 

<p class="intro">Choosing where to send a paper is always a difficult decision. Here are ten ways in which you will benefit by publishing your paper in <em>PLoS Neglected Tropical Diseases</em>.</p>

<ol>
	<li><strong>Wide dissemination.</strong> As an open-access journal, <em>PLoS Neglected Tropical Diseases</em> articles will always be freely available online, from our web site and from PubMed Central, to anyone with Internet access. Our <a href="license.action" title="Open Access license">open-access license</a> means that readers are free to download, print, distribute, and translate your work (see below). This means that your work will have the broadest possible audience: the entire world. And <a href="http://opcit.eprints.org/oacitation-biblio.html" title="The Open Citation Project - Reference Linking and Citation Analysis for Open Archives">recent studies</a> have begun to suggest that open-access articles are downloaded and cited more frequently. </li>
	<li><strong>Fast peer review by distinguished editors.</strong> <em>PLoS Neglected Tropical Diseases</em> is run by a distinguished international <a href="edboard.action" title="Editorial Board">team of editors</a> who are experts in their respective fields. Papers that are considered suitable for peer review by our Deputy Editors are assigned to an expert academic editor, who sends the paper to three independent peer reviewers. The result is an efficient, fair, and constructive review process. </li>
	<li><strong><a href="guidelines.action#presubmission" title="PLoS NTDs | Author Guidelines: Presubmission Inquiries">Presubmission inquiries</a>.</strong> We are happy to look at abstracts prior to submission and will let you know within 48 hours whether we will consider the full paper. </li>
	<li><strong>Rapid publication.</strong> Because we are primarily an online journal, once a paper is accepted we do not have to wait for space to become available in the print journal before the paper is published. The time between acceptance and online publication is normally around 6 weeks, and can be expedited under special circumstances. </li>
	<li><strong>Your research put in context.</strong> Each research article is accompanied by an Author Summary written by the article's authors, and edited for clarity by the <em>PLoS Neglected Tropical Diseases</em> editorial team. The summary is intended to be understandable by all medical professionals, whatever their specialty, and by the general public. </li>
	<li><strong>Post-publication activity.</strong> Peer review before publication is only the first step in the assessment process. Equally important are the readers' views of published papers. Our Notes, Comments, and Ratings facilities allow the scientific community to document, share and discuss views on the importance of your findings.</li>
	<li><strong>Author-friendly editing.</strong> Unlike other leading publications, we will not totally rewrite your paper to conform to house style. We will, of course, help authors whose first language is not English. In addition, we will not ask you to shorten your paper unnecessarily, although we do require papers to be written concisely. </li>
	<li><strong>No need to order reprints.</strong> Our open-access license means that anyone can reprint and distribute our content, so long as they credit the author and cite the original source. Commercial publishing companies make huge profits reprinting your work&#8212;now you have an alternative. </li>
	<li><strong>Your research has the chance to be highly influential.</strong> Many papers on neglected tropical diseases published in the PLoS journals have been downloaded large numbers of times, mentioned in national and international newspapers, and have had an important impact on health policy. For example, <a href="http://dx.doi.org/10.1371/journal.pmed.0030102" title="Hotez PJ et al. (2006) Incorporating a Rapid-Impact Package for Neglected Tropical Diseases with Programs for HIV/AIDS, Tuberculosis, and Malaria. PLoS Med 3(5): e102 doi:10.1371/journal.pmed.0030102">a paper </a>in <em>PLoS Medicine</em>, "Incorporating a Rapid-Impact Package for Neglected Tropical Diseases with Programs for HIV/AIDS, Tuberculosis, and Malaria", led to a <a href="http://www.earthinstitute.columbia.edu/malaria-ntd/" title="Earth Institute: The Quick Impact Initiative on Malaria and Neglected Tropical Diseases">UN mandate</a> to integrate control of the NTDs into the UN's malaria control efforts. </li>
	<li><strong>Publicity.</strong> We will send out regular press releases on all "media friendly" papers published by <em>PLoS Neglected Tropical Diseases</em> to ensure that papers have the greatest chance of being covered accurately by the media.</li>
</ol>


</div>
<!-- end : main contents -->
