<!-- begin : main content -->
<div id="content" class="static">

<h1>The Year of the Other Diseases</h1>
<h2>Remarks by Peter Hotez at the <a href="http://www.who.int/neglected_diseases/en/index.html" title="WHO | Control of Neglected Tropical Diseases">First WHO Global Partners' Meeting on NTD</a>, 19-20 April 2007</h2>

<p>Your Excellency Vice President Shein, His Royal Highness, Mrs. Hashimoto, Director-General Chan, Ladies and Gentlemen and Distinguished Guests, on behalf of the Sabin Institute and our Global Network for Neglected Tropical Disease Control, it is an extraordinary honor for me to address you today.</p>

<p>This has indeed been an extraordinary week.  Both from our Scientific and Technical Advisory Group held on Tuesday and Wednesday, today's amazing agenda, as well as a meeting on NTDs held in Washington last October it is clear that something remarkable and historical has happened over the last year.  Possibly never before have leaders from so many different disciplines come together to help the world's poorest people in such a visceral and tangible way.  Please stop and pause for a minute to think &#8212; representatives of the largest multinational pharmaceutical companies, working side by side with academicians and scientists, together with the Bill and Melinda Gates Foundation and other private philanthropies, together with their grantees &#8212; partnerships of the Global Network for Neglected Tropical Disease Control such as the SCI, ITI, GAELF, APOC, Sabin Institute, the Task Force, Helen Keller, Earth Institute, as well as the  Carter Center, together with the national health ministries, and perhaps most importantly, together with the district health managers and community distributors &#8212; all working together to deliver a package of NTD drugs, which will one day lift the world's poorest people out of poverty!</p>

<div class="quotes">
	<blockquote>
		<p>Today we recognize that an assault on the NTDs represents a significant and highly cost-effective new opportunity to reduce human misery and poverty.</p>
	</blockquote>
</div>

<p>Practically speaking what does it mean that the neglected tropical diseases, the NTDs that we speak about this week are the most common infections of poor people?  Try if you can to comprehend the enormity of six hundred million people, roughly one-fourth of the estimated 2.7 billion people who live on less than $2 per day, particularly children and their mothers, each with a dozen or more hookworms in their intestines collectively losing one-half million liters of blood every day of their lives?; and as a result never fulfilling their adult potential either physically or intellectually?  Imagine one-tenth of the world's poorest with schistosomiasis and as a result almost 10 million cases of hepatomegaly and 20 million cases of hydronephrosis?  Or some 40 million people with clinical evidence of lymphatic filariasis stigmatized and shunned by their community and in many cases even their own family because of their disfigured limbs and genitals.  In many ways this is worse than death &#8212;  human suffering on an almost unimaginable scale &#8212; literally one billion people with chronic, disabling, and stigmatizing diseases &#8212; ancient afflictions mentioned in the Quran, the Bible, Egyptian papyrus, the writings of Hippocrates, which have plagued humankind for centuries, which are still with us today. </p>

<p>But this is about to change.  Over this last year we have come together, aided by yet another remarkable group &#8212; the Department of Neglected Tropical Diseases at WHO under the stalwart leadership of Dr. Lorenzo Savioli and his truly talented senior associates, Dirk Engels, Denis Daumerie,  Maire Connolly, Jean Janin, Mike Nathan, and Morteza Zaim.  I think I can speak for my close colleagues who have worked with this WHO group for more than a decade that the Department of Neglected Tropical Diseases is one of the Crown Jewels of this house and we look forward everyday for the opportunity to work with them!  Together with the partners of the Global Network for Neglected Tropical Disease Control, we have launched an all assault on, not just on these diseases, but on poverty itself, because more than a decade of research has revealed that these NTDs are at the top of the list for why people remain trapped in destitution.  </p>

<p>The approach is two-pronged &#8212; First, a moral imperative to deliver simple treatments, preventive chemotherapy drugs, which we already know from past successes in Egypt, China and elsewhere will work well in controlling NTDs when they are administered to large populations, even in resource poor settings.  We are here this week to get the drugs out &#8212; the albendazole, mebendazole, diethylcarbamazine, ivermectin, praziquantel, and azithromycin  &#8212; and deploy them in a low-cost and cost-effective package.  Today, I am happy to announce that the private philanthropy, Geneva Global, has recently provided $8.8 million to the Global Network and its partners, SCI and Earth Institute, to deliver NTD drug packages for national control programs in Rwanda and Burundi. I also want to announce television and film star, Ms. Alyssa Milano's appointment as Honorary Ambassador for the Global Network along with her personal financial commitment to the WHO for the purchase of generic NTD drugs, diethylcarbamazine and praziquantel to in order combat lymphatic filariasis and schistosomiasis, respectively.  These activities will be highlighted at the upcoming mid-year meeting of the Clinton Global Initiative in New York this week. </p>

<p>Our second approach is to recognize that these drugs do not target all of the NTDs, so that we need to urgently step-up measures to conduct research and development for new control tools, new drugs and new diagnostics.  This also includes the development of new vaccines for NTDs.  Antipoverty vaccines for several NTDs are under development and clinical testing, including a new vaccine for leishmaniasis, schistosomiasis, onchocrciasis, and hookworm infection.  To increase global access to new research and development related to the NTDs, the Global Network in association with Nobel Laureate Harold Varmus and his Public Library of Science has recently created the PLoS Neglected Tropical Diseases, the first open access journal for these conditions.  In time, we anticipate that one day these vaccines will be folded in to the NTD drug package, so that our rapid impact package of today may look very different from our rapid impact package of tomorrow.  In principle, antipoverty vaccines for all of the NTDs could be developed and tested if resources were made available.  </p>

<p>Which brings us to our final point: Through Millennium Development Goal 6 the 2000 United Nations Millennium Declaration focused on HIV/AIDS and malaria as its essential infectious disease targets.  In response, the Group of 8 launched impressive initiatives such as the Global Fund, PEPFAR, PMI and others. These efforts are making a significant impact worldwide.  It is not well appreciated, however, that MDG 6 actually reads, "To Combat HIV/AIDS, malaria, and other diseases."  I want this year to be remembered as <em>The Year of the Other Diseases</em>, the NTDs.  Distinguished guests I would urge that together we call upon the G8 to take on the NTDs with the same urgency that they did for AIDS and malaria.  Through countless studies, many conducted by people in this room, it now must be firmly stated that tackling the NTDs has become our newest and perhaps our most important new weapon in our global fight for sustainable poverty reduction! Further, now strong evidence has emerged that NTDs overlap extensively with AIDS and malaria in many poor rural parts of sub-Saharan Africa where they increase susceptibility to AIDS and malaria, particularly for women and infants, while at the same time they significantly worsen the clinical course of these terrible illnesses.  Therefore, taking on the NTDs as a means to combat AIDS and malaria is creating a new sense of urgency like never before.  Today we recognize that an assault on the NTDs represents a significant and highly cost-effective new opportunity to reduce human misery and poverty. The assault has already begun, and if nurtured appropriately it will gain momentum in an unprecedented and effective manner.  </p>

</div>
<!-- end : main contents -->